### PR TITLE
Use Individual PRU.

### PR DESCRIPTION
**Pull request by ArthurSonzogni**
Refactor:
https://github.com/SAtacker/beagle-config/pull/27

Use a class to represent an individual PRU. This lead to simpler and
2x shorter code.

Moreover, the buttons about a PRU are group with the info about the PRU.

### CODE REVIEW

**Comment by ArthurSonzogni** [comment]
Hi @SAtacker 
Could you please take a look?

**Comment by ArthurSonzogni** [comment]
Note that I wasn't able to test locally on a real device. You might want to bring back the feature about checking the existence of the firmware maybe?

**Comment by SAtacker** [comment]
> Refactor:
> #27
> 
> Use a class to represent an individual PRU. This lead to simpler and
> 2x shorter code.
> 
> Moreover, the buttons about a PRU are group with the info about the PRU.

Thanks, @ArthurSonzogni !

**Comment by SAtacker** [comment]
> Note that I wasn't able to test locally on a real device. You might want to bring back the feature about checking the existence of the firmware maybe?

Yes actually the little info would be nice, I'll make the changes over your PR and send it on `dev` . Thanks!

**Pull request merged**
