### PR TITLE
Make the main menu to be resizeable.

### PR DESCRIPTION
**Pull request by ArthurSonzogni**
On small screen, some users may find it useful to be able to resize the
main menu to let more space to the content.

This patch make use of ResizableSplitLeft component.

### CODE REVIEW

**Comment by ArthurSonzogni** [comment]
https://user-images.githubusercontent.com/4759106/128925586-991edc22-246e-47d6-a165-2a827d24abc5.mp4

**Comment by SAtacker** [comment]
These are some really nice patches that enhance the UI and overall feel. :heart:

**Comment by ArthurSonzogni** [comment]
Ooops, could you please let me some time to update this patch. I put the exit button in the wrong container.

**Comment by ArthurSonzogni** [comment]
... and done!

**Pull request merged**
