### PR TITLE
Several improvements.

### PR DESCRIPTION
**Pull request by ArthurSonzogni**
A few improvement about the pull request:
https://github.com/SAtacker/beagle-config/pull/15

- This adds a component to interact with individual LEDs. This avoids managing an array of states.
- Instead of spawning new process for reading / writing files, use the C++ file API.
- Improve the UI a bit.

### CODE REVIEW

**Comment by SAtacker** [comment]
Thanks for this @ArthurSonzogni 
Although I guess there's some issue with the `trigger`. The issue is that it always sets `delay_on` and `delay_off` to 500.
And the buttons are not visible to me

**Comment by ArthurSonzogni** [comment]
Thanks for this @ArthurSonzogni
> Although I guess there's some issue with the trigger. The issue is that it always sets delay_on and delay_off to 500.

That's because you aren't running it with sudo.

> And the buttons are not visible to me

Please take a look at the last version. Now I display only one LED and a radiobox menu at the top. This sounds better to me.

At some point, we could provide a menu to select when to trigger a LED. And maybe a graph of its state, by pooling it periodically.

----

Could you merge this patch into the LED branch? And then land your LED branch if everything looks good to you?

**Comment by SAtacker** [comment]
It is very nice looking right now. But why did using a subprocess call worked without having to use `sudo` ?

**Comment by SAtacker** [comment]
```sh
debian@beaglebone:~$ sudo chmod 777 beagle-config 
debian@beaglebone:~$ ./beagle-config 
debian@beaglebone:~$ ls -l beagle-config 
-rwxrwxrwx 1 debian debian 4416752 Jul 10 21:42 beagle-config
debian@beaglebone:~$ ls -l /sys/class/leds/
total 0
lrwxrwxrwx 1 root root 0 Jul 10 20:59 bat100 -> ../../devices/platform/leds/leds/bat100
lrwxrwxrwx 1 root root 0 Jul 10 20:59 bat25 -> ../../devices/platform/leds/leds/bat25
lrwxrwxrwx 1 root root 0 Jul 10 20:59 bat50 -> ../../devices/platform/leds/leds/bat50
lrwxrwxrwx 1 root root 0 Jul 10 20:59 bat75 -> ../../devices/platform/leds/leds/bat75
lrwxrwxrwx 1 root root 0 Jul 10 20:59 beaglebone:green:usr0 -> ../../devices/platform/leds/leds/beaglebone:green:usr0
lrwxrwxrwx 1 root root 0 Jul 10 20:59 beaglebone:green:usr1 -> ../../devices/platform/leds/leds/beaglebone:green:usr1
lrwxrwxrwx 1 root root 0 Jul 10 20:59 beaglebone:green:usr2 -> ../../devices/platform/leds/leds/beaglebone:green:usr2
lrwxrwxrwx 1 root root 0 Jul 10 20:59 beaglebone:green:usr3 -> ../../devices/platform/leds/leds/beaglebone:green:usr3
lrwxrwxrwx 1 root root 0 Jul 10 20:59 green -> ../../devices/platform/leds/leds/green
lrwxrwxrwx 1 root root 0 Jul 10 20:59 red -> ../../devices/platform/leds/leds/red
lrwxrwxrwx 1 root root 0 Jul 10 20:59 wifi -> ../../devices/platform/leds/leds/wifi
lrwxrwxrwx 1 root root 0 Jul 10 20:59 wl18xx_bt_en -> ../../devices/platform/bt_en/leds/wl18xx_bt_en
debian@beaglebone:~$ 
```
Even then I am not able to use it without sudo

**Comment by ArthurSonzogni** [comment]
> It is very nice looking right now. But why did using a subprocess call worked without having to use sudo ?

It doesn't seem to work with a subprocess without sudo.

**Comment by SAtacker** [comment]
```
echo "10" > /sys/class/leds/bat100/delay_off 
echo "10" > /sys/class/leds/bat100/delay_on
```
This does

**Comment by SAtacker** [comment]
I'll figure it out later. Will create an issue for this if needed.

**Pull request merged**
