### PR TITLE
Break the UI into several pieces.

### PR DESCRIPTION
**Pull request by ArthurSonzogni**
Move the different panel into different files. This way, work can happen
in several of them independently.

### CODE REVIEW

**Comment by ArthurSonzogni** [comment]
Hello,

Just a preview of what I wanted to do. This is not ready yet and there a couple of things from the previous interface I liked a lot that I would like to bring back.

**Comment by SAtacker** [comment]
Thanks for this @ArthurSonzogni. I realize the idea of making it modular is very much needed.

**Comment by ArthurSonzogni** [comment]
Hi @SAtacker,

I believe this is ready. Could you please take a look?
I didn't managed to reproduce the previous style with 3 sub menu. I believe this could be easily done by implementing:
https://github.com/ArthurSonzogni/FTXUI/issues/126

**Comment by SAtacker** [comment]
Thanks for this @ArthurSonzogni. I haven't yet tried it, will report here asap.

**Comment by ArthurSonzogni** [comment]
I updated the patch. It is now containing multiple section, using the work from:
https://github.com/ArthurSonzogni/FTXUI/pull/131

Please let me know if you have comments on this patch.

**Comment by SAtacker** [comment]
@ArthurSonzogni it's so much better than `panel` and scrolling works too.

**Comment by ArthurSonzogni** [comment]
Great to hear!
Do you need anything from me, before merging this patch?

**Comment by SAtacker** [comment]
No @ArthurSonzogni. That's a lot of help already. :smile:

**Pull request merged**
