### PR TITLE
Add the about panel.

### PR DESCRIPTION
**Pull request by ArthurSonzogni**
Add a beagle logo.
Display the version and commit used to compile the application.

### CODE REVIEW

**Comment by ArthurSonzogni** [comment]
image

**Comment by ArthurSonzogni** [comment]
;-)
I used:
https://505e06b2.github.io/Image-to-Braille/

and the beagleboard logo.

**Comment by SAtacker** [comment]
[asciicast](https://asciinema.org/a/429900)
I added a button to view the complete logo

**Comment by ArthurSonzogni** [comment]
> I added a button to view the complete logo

Really nice!

**Comment by RobertCNelson** [comment]
Awesome logo @ArthurSonzogni

**Pull request merged**
